name: test
channels:
  - conda-forge
  - defaults
dependencies:
  - colorama
  - downloader-cli
  - ffmpeg-python
  - itunespy
  - musicbrainzngs
  - mutagen
  - pydes
  - pysocks
  - python
  - pyxdg
  - requests
  - rich
  - simber
  - spotipy
  - unidecode
  - urllib3
  - youtube-dl
  - youtube-search-python
  - ytmusicapi
  - pytest
  - pytest-cov
  - codecov
  - pip
  - isort
  - black
  - flake8
